# Generated by Django 3.1.4 on 2020-12-16 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_file', models.CharField(max_length=200)),
                ('out_file', models.CharField(max_length=200)),
                ('in_file_loc', models.IntegerField()),
                ('in_file_size', models.IntegerField()),
                ('in_tmstmp', models.DateTimeField(auto_now_add=True)),
                ('out_tmstmp', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
