# Generated by Django 3.1.4 on 2021-01-19 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210109_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convert',
            options={'ordering': ['-in_tmstmp']},
        ),
        migrations.AlterField(
            model_name='convert',
            name='in_tmstmp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 19, 13, 19, 48, 759800)),
        ),
        migrations.AlterField(
            model_name='convert',
            name='out_tmstmp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 19, 13, 19, 48, 759818)),
        ),
    ]
