# Generated by Django 3.1.4 on 2021-01-27 09:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_auto_20210119_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convert',
            name='in_tmstmp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 27, 9, 55, 18, 970960)),
        ),
        migrations.AlterField(
            model_name='convert',
            name='out_tmstmp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 27, 9, 55, 18, 970976)),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default='1000', verbose_name='balance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
