# Generated by Django 3.1.4 on 2021-03-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210317_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='converttransaction',
            name='confirm',
        ),
    ]
